config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do

    resources :reviews, only: [:new, :create, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5}, allow_nil: false
  validates :content, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(id: @restaurant.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:show, :new, :create]
  def new
    @review = Review.new
  end

  def show
  end

  def create
    @review = @restaurant.reviews.create(review_params)
    if @review.save
      redirect_to restaurant_path(id: @restaurant.id)
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  private
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/edit.html.erb
<h2>Edit the fields of <%= @restaurant.name %></h2>
<%= simple_form_for @restaurant do |f| %>
<%= f.input :name, placeholder: "Enter the restaurant name" %>
<%= f.input :address, placeholder: "Enter the address" %>
<%= f.input :phone_number, placeholder: "Enter the phone number" %>
<%= f.input :category, placeholder: "Enter the type of cuisine(i.e. italian, french, english, etc.)", :collection => %w[chinese italian japanese french belgian] %>
<%= f.submit "Submit your edit", class: "btn btn-info" %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="text-center">
  <div id="bannerimage">
    <h2>Restaurants</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="text-center">
    <ul>
      <% @restaurants.each do |restaurant| %>
      <li>
        <%= link_to(restaurant.name, restaurant) %> <br>
        Address: <%= restaurant.address %> <br>
        Phone No: <%= restaurant.phone_number %> <br>
        Cuisine: <%= restaurant.category %> <br>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <%= link_to "Create a new restaurant to add to our page!", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h2>Enter the fields of the restaurant</h2>
<%= simple_form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
    <% @restaurant.errors.full_messages.each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
  <%= f.input :name, placeholder: "Enter the restaurant name" %>
  <%= f.input :address, placeholder: "Enter the address" %>
  <%= f.input :phone_number, placeholder: "Enter the phone number" %>
  <%= f.input :category, placeholder: "Enter the type of cuisine(i.e. italian, french, english, etc.)" %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="text-center">
    <h2><%= @restaurant.name %></h2>
    <h3><%= @restaurant.address %></h3>
    <p><%= @restaurant.phone_number %></p>
    <p><%= @restaurant.category %></p>
    <%= link_to "Edit this resturant info", edit_restaurant_path %>

    <%= link_to "Write a review for #{@restaurant.name}", new_restaurant_review_path(@restaurant) %>
  </div>
</div>

app/views/reviews/new.html.erb
<h2><%= @restaurant.name %></h2>
<h3><%= @review.content %></h3>
<p><%= @review.rating %></p>
 <%= link_to "Return to the resturant's main page", restaurant_path(id: @restaurant.id) %>

<h2>Write a new review for <%= @restaurant.name %></h2>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h2><%= @restaurant.name %></h2>
<h3><%= @review.content %></h3>
<p><%= @review.rating %></p>
 <%= link_to "Return to the resturant's main page", restaurant_path %>